# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS  := xdp_modular_firewall xdp_firewall_module xdp_root xdp_odd_icmp_seq
USER_TARGETS :=

LIBBPF_DIR = ../libbpf/src/
COMMON_DIR = ../common

COPY_LOADER := xdp-mfw
COPY_STATS  := 

include $(COMMON_DIR)/common.mk
